#!/usr/bin/env bash
# PrimeChat — First-time setup
# Run: bash scripts/setup.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG="$ROOT/config"

echo "=== PrimeChat Setup ==="

# 1. config/app.php
if [ ! -f "$CONFIG/app.php" ]; then
    cp "$CONFIG/app.example.php" "$CONFIG/app.php"
    echo "[OK] config/app.php created from example"
else
    echo "[--] config/app.php already exists"
fi

# 2. config/database.php
if [ ! -f "$CONFIG/database.php" ]; then
    DB_HOST="${DB_HOST:-127.0.0.1}"
    DB_PORT="${DB_PORT:-3306}"
    DB_USER="${DB_USER:-primechat}"
    DB_PASS="${DB_PASS:-}"
    DB_NAME="${DB_NAME:-primechat}"
    DB_CHARSET="${DB_CHARSET:-utf8mb4}"

    cat > "$CONFIG/database.php" <<PHP
<?php
/**
 * PrimeChat — Database Configuration (auto-generated by setup.sh)
 */
\$requiredVars = ['DB_HOST', 'DB_PORT', 'DB_USER', 'DB_PASS', 'DB_NAME', 'DB_CHARSET'];
foreach (\$requiredVars as \$var) {
    if (!isset(\$_ENV[\$var])) {
        error_log("CRITICAL ERROR: Missing required environment variable: {\$var}");
        http_response_code(500);
        exit(json_encode(['success' => false, 'error' => 'Server Configuration Error']));
    }
}

define('DB_HOST', \$_ENV['DB_HOST']);
define('DB_PORT', \$_ENV['DB_PORT']);
define('DB_USER', \$_ENV['DB_USER']);
define('DB_PASS', \$_ENV['DB_PASS']);
define('DB_NAME', \$_ENV['DB_NAME']);
define('DB_CHARSET', \$_ENV['DB_CHARSET']);

class Database {
    private static ?Database \$instance = null;
    private PDO \$pdo;

    private function __construct() {
        \$dsn = sprintf('mysql:host=%s;port=%s;dbname=%s;charset=%s', DB_HOST, DB_PORT, DB_NAME, DB_CHARSET);
        \$options = [
            PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES   => false,
            PDO::ATTR_STRINGIFY_FETCHES  => false,
            PDO::MYSQL_ATTR_FOUND_ROWS   => true,
        ];
        try {
            \$this->pdo = new PDO(\$dsn, DB_USER, DB_PASS, \$options);
            \$this->pdo->exec("SET time_zone = '+05:30'");
        } catch (PDOException \$e) {
            error_log('Database connection failed: ' . \$e->getMessage());
            http_response_code(500);
            echo json_encode(['success' => false, 'error' => 'Database connection failed']);
            exit;
        }
    }
    private function __clone() {}
    public function __wakeup() { throw new \\Exception("Cannot unserialize singleton"); }
    public static function getInstance(): self { if (self::\$instance === null) self::\$instance = new self(); return self::\$instance; }
    public static function setInstance(?self \$instance): void { self::\$instance = \$instance; }
    public function getConnection(): PDO { return \$this->pdo; }
    public function query(string \$sql, array \$params = []): PDOStatement { \$stmt = \$this->pdo->prepare(\$sql); \$stmt->execute(\$params); return \$stmt; }
    public function lastInsertId(): string { return \$this->pdo->lastInsertId(); }
    public function beginTransaction(): bool { return \$this->pdo->beginTransaction(); }
    public function commit(): bool { return \$this->pdo->commit(); }
    public function rollback(): bool { return \$this->pdo->rollBack(); }
    public function inTransaction(): bool { return \$this->pdo->inTransaction(); }
}
PHP
    echo "[OK] config/database.php created — edit with your DB credentials"
else
    echo "[--] config/database.php already exists"
fi

# 3. config/session.php
if [ ! -f "$CONFIG/session.php" ]; then
    cat > "$CONFIG/session.php" <<'PHP'
<?php
/**
 * PrimeChat — Session Configuration
 */
if (php_sapi_name() !== 'cli') {
    ini_set('session.cookie_httponly', 1);
    ini_set('session.cookie_secure', isset($_SERVER['HTTPS']) ? 1 : 0);
    ini_set('session.use_strict_mode', 1);
    ini_set('session.cookie_samesite', 'Lax');
    ini_set('session.gc_maxlifetime', (string)(86400 * 7));
}
PHP
    echo "[OK] config/session.php created"
else
    echo "[--] config/session.php already exists"
fi

# 4. .env
if [ ! -f "$ROOT/.env" ]; then
    cp "$ROOT/.env.example" "$ROOT/.env" 2>/dev/null || cat > "$ROOT/.env" <<'ENV'
# PrimeChat Environment
APP_URL=http://localhost:8000
DB_HOST=127.0.0.1
DB_PORT=3306
DB_USER=primechat
DB_PASS=changeme
DB_NAME=primechat
DB_CHARSET=utf8mb4
ENV
    echo "[OK] .env created — edit with your values"
else
    echo "[--] .env already exists"
fi

# 5. uploads directory
mkdir -p "$ROOT/public/uploads" "$ROOT/public/avatars"
echo "[OK] Upload directories ready"

echo ""
echo "=== Next steps ==="
echo "1. Edit config/database.php with your DB credentials"
echo "2. Edit .env with your APP_URL and DB_PASS"
echo "3. Run: php scripts/migrate.php"
echo "4. Point your web server DocumentRoot to: $ROOT/public"
